- name: install and start nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true    

#  - name: verify nginx service status
#    ansible.builtin.service_facts:   
# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps32 02-nginx.yaml
